name    'Enrise-Mariadb'
version '0.2.0'
source 'UNKNOWN'
author  'Dolf Schimmel (Freeaqingme) / Enrise - www.enrise.com'
license '3-Clause BSD license'
summary 'Installs MariaDB'
description 'Adds the MariaDB APT repository, installs MariaDB.'
project_page 'http://www.github.com/Enrise/Puppet-MariaDB'

dependency 'example42/mysql', '>= 2.0'
dependency 'puppetlabs/apt', '>= 1.1.0'
